#http://192.168.1.72:9000/login?fly_port=52903
#bearer cdGn9MCv3GjNKYjXzBbLnB8sseqWr5dlAAAAAA
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: neogicel/spring-hello
    tag: latest

resources:
- name: hello-world-spring
  type: git
  source:
      uri: https://github.com/neogiciel/hello-world.git

- name: docker-images-hello-world-spring
  type: docker-image
  source:
      repository: neogicel/spring-hello
      username: neogicel
      password: Patrice88$
#- name: k8s
#  type: kubernetes
#  source:
      #kubeconfig: https://192.168.49.2:8443
#      api_server_uri: https://192.168.49.2:8443
#      namespace: default
#      certificate_authority_data: MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5pa3ViZUNBMB4XDTIzMTEyMjE3NDcyMFoXDTMzMTEyMDE3NDcyMFowFTETMBEGA1UEAxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOU0ZoIvjH7jPcqaE76iMbrH04isxjQRuD7ZQ9J6A0Nu3taVnDQ96OYSFcjdHTDqnxxWnoNzEtIzpY4csXJP740teEPZJZKu4YkAOinVPuYAV+xfuuiYTGOyuiF924jwmZMExbPz0GQxXyaKR19dSNe0uKsSwxk8aaZSfv0xzE7kMLE44/5d/FxifEpgi8j54cZA4H5EgzJAE6xZdH26x2EouwjKREhXev0VHlAm2tJoxfb+BXAwbjDHFoEduZmvTYrUmq3SURHNpoXpIRdGndzr8KuQnK/xgs2xKcmrfPHwtCZYYUMCVsP1E7ph3Hz8TPv5GNqNdEUMd1VOPyu6FSECAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTkvg5kTbS23/pRNzZmrU+5HQpmSzANBgkqhkiG9w0BAQsFAAOCAQEA171yfyfWRwVycqgrfulidfqM4jQ9bTIl7rtU02jpX2JHfqbGBYKAvUYo3gJxLfKA6gCFfWv8DMEkGPqLteZwJ9GCCIHi+3kFFOZHOF1B4wZEX+aXZPEUTho0idb40lxqeMKxnYfEiPRzxejbMWwXOS4L+ttWV/warDfxKG8wE/I2bO+xpQtJGc5EFKep6YiRvLB0jj1fwUvKQfE74W+NAjtwWt1DDaMxNEpGKQ5b7OisPLCHLBYgH7cnB2LCh4khKml9HKT5UzHW3gYp7YiIt9PIzRnsd3mDrBpdawWtNfeSEPdAeoSgEuMGmUkwhgARGmSkQGS8lp8/x+sIiraSRQ==
#      token: cdGn9MCv3GjNKYjXzBbLnB8sseqWr5dlAAAAAA
jobs:
- name: test
  plan:
  - get: hello-world-spring
    trigger: true
  - task: mvn-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: hello-world-spring
      run:
        path: "mvn"
        args:
          - -f
          - hello-world-spring/pom.xml
          - clean
          - test

- name : package
  public: true
  serial: true
  plan:
  - get: hello-world-spring
    trigger: true
    passed: [test]
  - task: mvn-package
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: hello-world-spring
      run:
        path: "mvn"
        args:
          - -f
          - hello-world-spring/pom.xml
          - clean
          - package
      outputs:
      - name: spring-boot-service-out
        path: hello-world-spring
  - put: docker-images-hello-world-spring
    params:
        build: spring-boot-service-out

- name: add-regcred-to-k8s
  plan:
  - task: push-regcred
    config:
      platform: linux

      image_resource:
        type: registry-image
        source:
         #repository: dtzar/helm-kubectl
          repository: neogicel/spring-hello
      run:
        path: /bin/sh
        args:
          - -cx
          - |
           # delete secret first and ignore if not found
           #kubectl get pods
            kubectl --server="http://dev.neogiciel.com" --token="cdGn9MCv3GjNKYjXzBbLnB8sseqWr5dlAAAAAA" -n default --ignore-not-found=true


#- name : deploy
#  public: true
#  serial: true
#  plan:
#  - get: hello-world-spring
#    trigger: true
#    passed: [test]
#  - task: kubernetes-deployt
#    config:
#      platform: linux
#      inputs:
#        - name: hello-world-spring
#      run:
#        path: kubectl"
#        args:
#          - get pods      
- name: hello-world-job
  plan:
  - task: hello-world-task
    config:
     platform: linux
     image_resource:
       type: registry-image
       source:
         repository: busybox
     run:
        path: echo
        args: ["Hello world!"]