resource_types:
- name: k8s
  type: docker-image
  source:
    repository: neogicel/spring-hello
    tag: latest

resources:
- name: k8s
  type: k8s
  source:

    api_server_url: https://172.16.10.11:6443

    # or use kubeconfig
    kubeconfig: |
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority: /home/neogiciel/.minikube/ca.crt
          extensions:
          - extension:
              last-update: Tue, 12 Dec 2023 00:44:20 CET
              provider: minikube.sigs.k8s.io
              version: v1.32.0
            name: cluster_info
          server: https://192.168.49.2:8443
        name: minikube
      contexts:
      - context:
          cluster: minikube
          extensions:
          - extension:
              last-update: Tue, 12 Dec 2023 00:44:20 CET
              provider: minikube.sigs.k8s.io
              version: v1.32.0
            name: context_info
          namespace: default
          user: minikube
        name: minikube
      current-context: minikube
      kind: Config
      preferences: {}
      users:
      - name: minikube
        user:
          client-certificate: /home/neogiciel/.minikube/profiles/minikube/client.crt
          client-key: /home/neogiciel/.minikube/profiles/minikube/client.key

    skip_tls_verify: false
    namespace: default

- name: hello-world-spring
  type: git
  source:
    uri: https://github.com/neogiciel/hello-world.git
- name: docker-images-hello-world-spring
  type: docker-image
  source:
      repository: neogicel/spring-hello
      username: neogicel
      password: Patrice88$
jobs:
- name: test
  plan:
  - get: hello-world-spring
    trigger: true
  - task: mvn-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: hello-world-spring
      run:
        path: "mvn"
        args:
          - -f
          - hello-world-spring/pom.xml
          - clean
          - test

- name : package
  public: true
  serial: true
  plan:
  - get: hello-world-spring
    trigger: true
    passed: [test]
  - task: mvn-package
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: hello-world-spring
      run:
        path: "mvn"
        args:
          - -f
          - hello-world-spring/pom.xml
          - clean
          - package
      outputs:
      - name: spring-boot-service-out
        path: hello-world-spring
  - put: docker-images-hello-world-spring
    params:
        build: spring-boot-service-out

- name: deploy
  public: true
  serial: false
  plan:
      - get: hello-world-spring
        trigger: false
        passed: [package]

      - put: k8s
        params:
          status_check_timeout: 60
          command_timeout: 30
          file: 
          #  - hello-world-spring/ci/deployment.yaml