resource_types:
  - name: kubectl-resource
    type: docker-image
    source: 
      repository: neogicel/spring-hello
      tag: latest

resources:
- name: hello-world-spring
  type: git
  source:
    uri: https://github.com/neogiciel/hello-world.git
- name: docker-images-hello-world-spring
  type: docker-image
  source:
      repository: neogicel/spring-hello
      username: neogicel
      password: Patrice88$

- name: kubectl
  type: kubectl-resource
  source:
      api_server_uri: https://192.168.49.2:8443
      namespace: default
      certificate_authority_data: Y29uY291cnNlLXdlYgo=
      token: 1633


jobs:
- name: test
  plan:
  - get: hello-world-spring
    trigger: true
  - task: mvn-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: hello-world-spring
      run:
        path: "mvn"
        args:
          - -f
          - hello-world-spring/pom.xml
          - clean
          - test

- name : package
  public: true
  serial: true
  plan:
  - get: hello-world-spring
    trigger: true
    passed: [test]
  - task: mvn-package
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: hello-world-spring
      run:
        path: "mvn"
        args:
          - -f
          - hello-world-spring/pom.xml
          - clean
          - package
      outputs:
      - name: spring-boot-service-out
        path: hello-world-spring
  - put: docker-images-hello-world-spring
    params:
        build: spring-boot-service-out

- name: deploy
  public: true
  serial: false
  plan:
      - get: hello-world-spring
        trigger: false
        passed: [package]

      - put: kubectl
        params:
          file: "hello-world-spring/ci/deployment.yaml"